title: Feihong Liu
logo: /assets/img/me.jpg
description: fml5147@psu.edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
postimage: /assets/img/dambreak.png
postimagedescription: Dambreak modeled by incoming LEDS2D
postimage: /assets/img/slumptest.png
postimagedescription: Slump test modeled by incoming LEDS2D